//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionDeStock
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bon()
        {
            this.Details_Bon = new HashSet<Details_Bon>();
        }
    
        public int id_Bon { get; set; }
        public System.DateTime Date_Bon { get; set; }
        public int id_Client { get; set; }
        public string Designation { get; set; }
        public Nullable<int> id_Libreur { get; set; }
        public Nullable<int> id_Demandeur { get; set; }
        public string Type { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Personnel Personnel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Details_Bon> Details_Bon { get; set; }
    }
}
