//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionDeStock
{
    using System;
    using System.Collections.Generic;
    
    public partial class BonLivraison
    {
        public int id { get; set; }
        public int id_Affaire { get; set; }
        public string Reference { get; set; }
        public string Designation { get; set; }
        public int Quantite { get; set; }
        public string PrixU { get; set; }
        public string PrixT { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
