//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionDeStock
{
    using System;
    using System.Collections.Generic;
    
    public partial class Details_Bon
    {
        public int IdèDetail { get; set; }
        public int idBon { get; set; }
        public int idProduit { get; set; }
        public string Reference { get; set; }
        public int Quantite { get; set; }
        public string PrixU { get; set; }
        public string Designation { get; set; }
    
        public virtual Bon Bon { get; set; }
        public virtual Produit Produit { get; set; }
    }
}
